### ISSUE TITLE
Dependency error on Linux Mint

### ISSUE THREAD

**Issue by federicosnobohm** [Shatur95/Crow-Translate#10]
i cant install in linux mint it says "dependecies error"

**Comment by Shatur95** [comment]
Could you provide terminal output?

**Comment by VolkMilit** [comment]
@federicosnobohm, I belive it's my fault. I absolutely forget that devscripts can't install dependencies automatically. Check out this [commit](https://github.com/Shatur95/Crow-Translate/pull/11/commits/23a103f0dbe57130da51762e8cc94f80124f3d92).

**Comment by Shatur95** [comment]
Now you can try rebuilding the package using [automatic script](https://github.com/Shatur95/Crow-Translate#automatic-script).
