### ISSUE TITLE
Add close button to popup window

### ISSUE THREAD

**Issue by hexauniverse** [Shatur95/crow-translate#12]
В некоторых ситуациях тап по пустому месту не работает, например когда я перехожу в другое основное окно и пытаюсь кликнуть на него. По крайней мере так происходит в wayland.

P.S. Спасибо за прекрасную программу. Наконец кто-то додумался сделать аналог qtranslate для линукс)

**Comment by hexauniverse** [comment]
> я могу добавить поддержку хоткея по закрытию окна (в настройках есть) во всплывающее окно.
Сейчас работает клавиша esc, но иногда она закрывает сначала окно основной программы. В целом можно добавить.

Я установил qt5-wayland и сделал `crow -platform wayland`, в результате вылезло `Unknown option 'p'.`.
Также пробовал через переменную `QT_QPA_PLATFORM=wayland` - вылезает `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
`
Это странно, другая qt-программа запускается в обоих случаях. Есть идеи?

**Comment by hexauniverse** [comment]
нашел вот это: https://unix.stackexchange.com/a/450699
у меня как раз 5.11.1, сейчас попробую откатиться

**Comment by hexauniverse** [comment]
Вроде бы откатил все нужные пакеты до 5.11.0rc2, но приложение перестало запускаться вообще (вернее запускается, но окна нет и вызвать его не могу). Возможно, я что-то сделал не правильно, но видимо гном требует последнюю версию. Но проблема явно на моей стороне

**Comment by Shatur95** [comment]
Не факт, есть вероятность, что это проблема совместимости окнного менеджера Gnome для Wayland и реализации этого протокола в Qt. Допилят еще :D

**Comment by hexauniverse** [comment]
обновил обратно, попробовал `unset XDG_SESSION_TYPE` (как я сразу не додумался)
И ситуация такая же как с 5.11.0rc2

**Comment by hexauniverse** [comment]
Да, буду жлать когда допилят

**Comment by Shatur95** [comment]
Угу. У меня тоже Arch Linux, но сессия на X11 и сейчас нет возможности подтвердить баг. Но я тут в любом случае безсилен. Постараюсь на неделе добавить поддержку хоткея.
