### ISSUE TITLE
Esc shortcut

### ISSUE THREAD

**Issue by akkk33** [Shatur95/crow-translate#14]
Please add an 'Esc' hot key to empty the window at once instead of using "Backspace" button to delete letter by letter.

**Comment by Shatur95** [comment]
But you can also use Ctrl + A and start typing new text to overwrite the previous one.

**Comment by akkk33** [comment]
Well ,, If the box loses focus (like selecting some words from the translated text) , You have to click on the box to `Ctrl` + `A`.
So I think an `Esc` key shortcut that doesn't being affected by elements focus would be better.
I've made a small python app with QT, If this app was made with python, I'd done it and made a pull request instead of bothering you.. But unfortunately I don't understand C++ :(

**Comment by Shatur95** [comment]
I think this hotkey is superfluous. But I changed the focus traversal order of the elements. Now the input field is automatically in focus when the application is opened.

**Comment by akkk33** [comment]
That's cool, Thanks for your awesome work :heart:
