### ISSUE TITLE
Missing toolbar icons

### ISSUE THREAD

**Issue by jcalonso** [Shatur95/crow-translate#15]
Hi!
I'm using crow-translate installed from Arch AUR
https://aur.archlinux.org/packages/crow-translate/

And for some reason is not displaying the toolbar icons.
![2018-11-27_09-16](https://user-images.githubusercontent.com/664474/49071110-27307900-f225-11e8-895b-8b7441be71d7.png)

Any ideas?

**Comment by Shatur95** [comment]
Hello!
What DE / VM and icon theme are you using? Is there such a problem in other Qt applications?
I assume you don't have Qt applications [configured](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications).

**Comment by jcalonso** [comment]
I'm using i3 WM and using ePapirus icon theme, I use lxAppearance to manage them.

Could it be that ePapirus doesn't have the required icons?

**Comment by Shatur95** [comment]
I assume this helped.
