### ISSUE TITLE
Add preferred languages

### ISSUE THREAD

**Issue by hitman72ita** [Shatur95/Crow-Translate#8]
The ideal (for me) would be like in qtranslator (windows). can you add an option if text ISN'T in italian (for example), translate to italian. if text is in italian, tranlate in english. thank you

**Comment by Shatur95** [comment]
A good idea! Now I'm working on the checkbox "Automatically translate". After that I'll add the preferred languages ​​as in QTranslate, as you suggested.

**Comment by Shatur95** [comment]
I decided to do this like Google Translate. Now I have implement the selection of the previous language if the source language and the target language are the same.
In the next release, I will implement a similar check when translating with language auto-detection.
I think that such an realization is more suitable for the interface with buttons.

**Comment by hitman72ita** [comment]
thank you for updating this awesome program :-) because of my bad English I have not succeeded in making me understand. in windows there is a program called "QTranslate" (not "google translator") that (for me) has a nice option to translate text in ALL languages detected to main language, and main language to secondary language, without any click or choice. I have made a small video, perhaps so it is clearer. thank you again
[](https://www.youtube.com/watch?v=ETlRCkNFagQ&feature=youtu.be)

**Comment by Shatur95** [comment]
@hitman72ita Yes, I understood you correctly :) But I then decided to do this as in Google Translate (automatically select the previous checked language if the source and target language are the same).
But after a while I realized that it was not very convenient (as in Google Translate) and it would be better to add preferred languages ​​too (as in QTranslate).
So I'll try to add this feature as soon as possible :)
